#!/usr/bin/env python
# coding=utf8

import yaml

from leagueoflegends.scrape import parse_items, item_file_name

if '__main__' == __name__:
	d = parse_items()
	with file(item_file_name, 'w') as f:
		yaml.dump(d, f)
	print "wrote",item_file_name
