#!/usr/bin/env python
# coding=utf8

import sys
import yaml

import networkx

from leagueoflegends import ItemGraph, TrackingInventory, Build

if 3 != len(sys.argv):
	print "usage: %s DB_FILE ITEMBUILD_FILE" % (sys.argv[0])
	sys.exit(1)

db = ItemGraph.from_item_file(sys.argv[1])
build = Build.from_build_file(db, sys.argv[2])

print build.to_purchase_yaml()
